# Generated by Django 4.2.7 on 2023-11-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_name_alter_menu_nesting_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
